name: Access cache
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1,*/6 * *'

jobs:
  test:
    name: Accessing cache to prevent deletion
    runs-on: ubuntu-latest
    steps:
    - name: Restore toolchains from cache
      uses: actions/cache/restore@v4
      with:
        path: toolchains
        key: toolchains
        lookup-only: true
